### PR TITLE
Allow changing the GitHub API base URL via the INSTALLER_DOWNLOAD_URL env var

### PR DESCRIPTION
**Pull request by gaborbernat**
Resolves https://github.com/axodotdev/cargo-dist/issues/1449

### CODE REVIEW

**Review by mistydemeo — COMMENTED** [review]
Thank you! This is looking good, and thanks so much for the tests.

Just one comment - the `INSTALLER_DOWNLOAD_URL` environment variable means something very different to the installer. There it's the root URL at which the installer artifacts can be found, while here it's the GitHub API root. Those two URL structures aren't usually going to be compatible, so we'll want to pick a different name here - that way the two options can be set independently of each other and won't interfere.

**Comment by mistydemeo** [comment]
Sorry if there was a mixup in the original issue over the choice of variable name!

**Comment by gaborbernat** [comment]
> Thank you! This is looking good, and thanks so much for the tests.
> 
> Just one comment - the `INSTALLER_DOWNLOAD_URL` environment variable means something very different to the installer. There it's the root URL at which the installer artifacts can be found, while here it's the GitHub API root. Those two URL structures aren't usually going to be compatible, so we'll want to pick a different name here - that way the two options can be set independently of each other and won't interfere.

For my personal use case, that would be a disadvantage, not an advantage. Yes, these two might mean slightly different, but ultimately, from an end-user point of view, both of them are, hey, here are where the artifacts are hosted at. some artifacts are installer packages, other are github releases and api metadata are really just implementation details from an end user point of view.

So I would suggest that you reconsider that. Having to set two separate environment variables to install and update my package would cause more confusion than how much benefit it would provide in my opinion. They might be beneficial for the one maintaining the site but would be a problem for the end users.

**Comment by gaborbernat** [comment]
@mistydemeo so how about a compromise of: use `UPDATER_DOWNLOAD_URL` if set, if not then try with `INSTALLER_DOWNLOAD_URL` and if that is also not set use `https://api.github.com`. This way if they differ user can set accordingly but if it's the same we can reuse the same env-var?

**Comment by axel-kah** [comment]
👍 for `INSTALLER_BASE_URL` not pointing to the "installer" but to be used to point it to the github (mirror) base URL.

**Review by mistydemeo — APPROVED** [review]
Merging this and our followup pull request. Thank you again very much for this!

**Comment by gaborbernat** [comment]
Do you have a timeline when we should expect this feature to be available for uv?

**Pull request merged**
